export interface Team {
    id: number,
    name: string,
    divisionRank: number,
    wins: number,
    losses: number,
    ot: number,
    regulationWins: number,
    goalsAgainst: number,
    goalsScored: number,
    points: number,
    divisionL10Rank: number,
    divisionRoadRank: number,
    divisionHomeRank: number,
    conferenceRank: number,
    conferenceL10Rank: number,
    conferenceRoadRank: number,
    conferenceHomeRank: number,
    leagueRank: number,
    leagueL10Rank: number,
    leagueRoadRank: number,
    leagueHomeRank: number,
    wildCardRank: number,
    row: number,
    gamesPlayed: number
}